### ISSUE TITLE
certificates are piling up on every new instalation

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-incubator/local-kyma#2]
Is it possible to reuse old certificates? The more we do local installs, the more certificates we have
![image](https://user-images.githubusercontent.com/478866/87664155-1370b800-c765-11ea-8278-82a968a053bc.png)

**Comment by pbochynski** [comment]
I had a plan to add the conditional in the script that checks if certificate file exists in current folder and contains valid certificate. In that case skip cert-manager installation and create kyma-gateway-certs secret from file. But I do not like to introduce another logic in bash script and postponed it until we have support in CLI. I would imagine another flag where you can pass certificate to be used instead of using cert-manager.

**Comment by pbochynski** [comment]
I wanted to keep support for cert-manager, but after a while, I think it doesn't make sense. I will replace cert-manager with static certificate valid for 10 years. Something like this: https://github.com/kyma-project/kyma/tree/master/installation/certs/workspace/raw

**Comment by pbochynski** [comment]
Solved by removing cert-manager and using static certificate valid for 10 years.
